### ISSUE TITLE
Assignment 1 is Ready for Viewing

### ISSUE THREAD

**Issue by brianaflynn** [VIS-2129-F2020/bflynn-vis#1]
Hi Carole and Taelor,

My first assignment can be found at this link: https://vis-2129-f2020.github.io/bflynn-vis/VisAssignment1. 

Thanks very much,
Briana

**Comment by bauranov** [comment]
Stellar work! The only comment I have is that in the first plot you could have used different colors instead of shades of blue, the chart would be easier to read, Keep up the good work!
