### ISSUE TITLE
Assignment 2 Ready for Viewing

### ISSUE THREAD

**Issue by brianaflynn** [VIS-2129-F2020/bflynn-vis#2]
Hi Carole and Alex,

My assignment 2 is now ready for viewing at this link: https://vis-2129-f2020.github.io/bflynn-vis/VisAssignment2.html

Thanks so much,
Briana

**Comment by bauranov** [comment]
Well done! Here are some comments:
- At the beginning of a code chunk add {r, message=FALSE,warning=FALSE} to suppress messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (such as in the section Loading Data, or Transforming the map). If there is such text, remove it with the code I mentioned above.
- Sometimes it makes sense to add names of the countries to the map. You can do that with geom_label() and geom_text().
- I like inferno palette, it reminds me of Lion King. 
Keep up the good work!
