### ISSUE TITLE
Vis Assignment 3 is ready for viewing

### ISSUE THREAD

**Issue by brianaflynn** [VIS-2129-F2020/bflynn-vis#3]
Hi there,

Assignment 3 is ready for viewing at this link: https://vis-2129-f2020.github.io/bflynn-vis/VisAssignment3

Thanks very much!
Briana

**Comment by bauranov** [comment]
The last two plots are not very clear. The color in Figure 5b (white) makes me think there is no data for these neighborhoods. In the last plot, another color for MSD might work better. Other than that, good work!
