### ISSUE TITLE
Vis Assignment 4 is ready for viewing

### ISSUE THREAD

**Issue by brianaflynn** [VIS-2129-F2020/bflynn-vis#4]
Hi all,

My fourth assignment can be viewed at this link: https://vis-2129-f2020.github.io/bflynn-vis/Assignment4vis.html

Thank you!
Briana

**Comment by bauranov** [comment]
Great work! I wonder if increasing the transparency of the walk and bikesheds would make the third map clearer... It is difficult to make it pretty with a lot of points on the map.
