### ISSUE TITLE
Assignment 6 is ready for viewing

### ISSUE THREAD

**Issue by brianaflynn** [VIS-2129-F2020/bflynn-vis#6]
Hello,

My interactive map of homeless shelters and affordable housing development in LA County, with median home values by Census Tract in the basemap, can be viewed here:  https://vis-2129-f2020.github.io/bflynn-vis/map1

I want to note that Jiwon walked me through adding multiple grouped layers to my map and was incredibly helpful.

Thanks so much,
Briana

**Comment by c-voulgaris** [comment]
Thanks! Please submit the html file via Canvas.
